from typing import Generator, List
import csv

from Factories.user_factory import UserFactory



class User:

    num_users: int = 1000000
    file_name: str = 'generated_users.csv'
    fields: List[str] = [
        'user_id',  # unique
        'first_name',
        'last_name',
        'email',  # unique
        'phone_number',  # unique
        'date_of_birth',
        'address',
        'city',
        'state',
        'country',
        'zip_code',
        'username',  # unique
        'password',
        'account_created',
        'is_active',

    ]



    @classmethod
    def __init__(cls,umn_users:int =1000000,file_name:str ='generated_users.csv') -> None:
        cls.num_users = umn_users
        cls.file_name = file_name


    @classmethod
    def add_header_fields_to_csv_file(cls)-> None:

        """
           add first row in csv file , its contain name of fields

        """

        with open(cls.file_name, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(cls.fields)


    @classmethod
    def add_generated_user_with_faker_to_csv_file(cls):
        """
               add users generated by Faker module to csv file
        """

        seeder:UserFactory=UserFactory(cls.num_users)
        users:Generator=seeder.create_user_with_fake_data()

        with open(f'{cls.file_name}', 'a') as csvfile:
                writer = csv.writer(csvfile)
                writer.writerows(users)




